name: homing
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.0.6
  image_picker: ^0.8.4+3
  image: ^3.0.1

  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/logo_homing.png"

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo_homing.png
    - lib/images/casa1.png
    - lib/images/PuntosNavegacion.png
    - lib/images/casa2.png
    - lib/images/CasaTuxtla.jpg
    - lib/images/user1.png
    - lib/images/casa3.png
    - lib/images/IconUser.png
